# version: "3.12"

networks:
  default:


services:
  api:
    container_name: url_shortener
    build:
      context: .
    command: sh /app/scripts/start.sh
    ports:
      - "8000:8008"
    env_file:
      - .env.prod
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

    networks:
      - default

  db:
    container_name: postgres
    image: postgres:16

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env.prod
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - default

volumes:
  pgdata:
