networks:
  default-test:


services:
  api-test:
    container_name: url_shortener_test
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest -v
    ports:
      - "8000:8000"
    env_file:
      - .env.test.prod
    volumes:
      - .:/app
    depends_on:
      test_db:
        condition: service_healthy

    networks:
      - default-test

  test_db:
    container_name: postgres-test
    image: postgres:16

    ports:
      - "5433:5432"

    env_file:
      - .env.test.prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - default-test
