# version: "3.12"

networks:
  default-test:


services:

  test_db:
    container_name: postgres-test
    image: postgres:16

    volumes:
      - pgdatatest:/var/lib/postgresql/data
    ports:
      - "5433:5432"

    env_file:
      - .env.test.local
    # env_file:
    #   - .env.test.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - default-test

volumes:
  pgdatatest:
