version: "3"

networks:
  default:


services:
  api:
    container_name: url_shortener
    build:
      context: .
    # command: uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8008
    command: sh /app/scripts/start.sh
    ports:
      - "8000:8008"
    env_file:
      - .env.prod
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default

  db:
    container_name: url_db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_db:
