networks:
  default:


services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx_local.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/html/static/

    networks:
      - default

  db:
    container_name: postgres
    image: postgres:16

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 30s
      retries: 5
    networks:
      - default

volumes:
  pgdata:
